# Use uma imagem base Python com OpenCV
FROM python:3.9

# Copie o código Python para o diretório de trabalho do contêiner
COPY questao_1.py /app/questao_1.py

# Defina o diretório de trabalho
WORKDIR /app

# Instale as bibliotecas necessárias
RUN pip install opencv-python-headless numpy

# Comando padrão para ser executado quando o contêiner for iniciado
CMD ["python", "questao_1.py"]
