# Imagem base Python com OpenCV
FROM python:3.9

# Instala as bibliotecas necessárias
RUN pip install opencv-python-headless numpy

# Copia os arquivos necessários para dentro do contêiner
COPY questao_1.py /
COPY airport_gray.png /
COPY airport_gray_noisy.png /

# Comando padrão para ser executado quando o contêiner for iniciado
CMD ["python", "/questao_1.py"]
