# Imagem base Python com OpenCV
FROM python:3.9

# Instala as dependências necessárias
RUN pip install opencv-python-headless numpy

# Copie os arquivos necessários para dentro do contêiner
COPY questao_2_a.py /
COPY airport.png /

# Comando padrão para ser executado quando o contêiner for iniciado
CMD ["python", "/questao_2_a.py"]
